### ISSUE TITLE
[sync] Switch to PCG for random number generation

### ISSUE THREAD

**Issue by prateek** [m3db/m3x#195]
As mentioned in https://github.com/golang/go/issues/21835, rand.NewSource is a 5K alloc. We should use https://github.com/MichaelTJones/pcg instead - it's *much* faster and only allocates 8/16 bytes. 

This will help latencies *a lot* during the OnDemand growth of the PooledWorkerPool.

**Comment by richardartoul** [comment]
Closed by #196
